[package]
name = "synthetic-dev/mydatastore"
description = "A simple promise based datastore wrapper"
version = "1.1.3"
license = "MIT"
authors = ["SyntheticDev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "sleitnick/comm@^0.1"
Signal = "sleitnick/signal@^1.0.1"
Promise = "evaera/promise@^3.1.0"
TableUtil = "sleitnick/table-util@1.1.1"